# Generated by Django 5.2.17 on 2026-09-09 05:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_default', models.BooleanField(default=False, help_text='Default price book applied when no customer-specific schedule is assigned.')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_books', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_books', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Price Book',
                'verbose_name_plural': 'Price Books',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('goods', 'Physical Goods'), ('service', 'Professional Service'), ('digital', 'Digital Software / License'), ('subscription', 'Recurring Subscription')], default='goods', max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('taxable', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True, help_text='Track stock levels and warehouse allocations for physical goods.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum_quantity', models.PositiveIntegerField(default=1, help_text='Minimum order quantity required to qualify for this price entry.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='organizations.organization')),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.pricebook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='sales.product')),
            ],
            options={
                'verbose_name': 'Price Book Entry',
                'verbose_name_plural': 'Price Book Entries',
                'ordering': ['price_book', 'product'],
                'unique_together': {('price_book', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='sales.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sales.productcategory'),
        ),
        migrations.CreateModel(
            name='TieredDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum order threshold for this tier.')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Upper threshold for tier. Leave blank for unbounded/infinity.', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed_price', 'Fixed Unit Price ($)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage off base price (e.g. 15.00 for 15%) or overridden fixed unit price.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_discounts', to='organizations.organization')),
                ('price_book_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_discounts', to='sales.pricebookentry')),
            ],
            options={
                'verbose_name': 'Tiered Discount',
                'verbose_name_plural': 'Tiered Discounts',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('unit', 'Count / Unit'), ('time', 'Time / Duration'), ('weight', 'Weight / Mass'), ('length', 'Length / Distance'), ('volume', 'Volume / Liquid'), ('area', 'Surface Area')], default='unit', max_length=30)),
                ('is_base_unit', models.BooleanField(default=True, help_text='Designates the reference standard unit for this category.')),
                ('ratio_to_base', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Multiplier to convert this unit into the category base unit.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['category', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sales.unitofmeasure'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'sku')},
        ),
    ]
