# Generated by Django 5.2.17 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebook',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
