# Generated by Django 5.2.17 on 2026-09-09 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_phase9'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_8941e0_idx',
            old_name='projects_pr_organiz_8f6e4e_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_3b122b_idx',
            old_name='projects_pr_organiz_0bb8c3_idx',
        ),
        migrations.RenameIndex(
            model_name='projectactivity',
            new_name='projects_pr_project_ca3859_idx',
            old_name='projects_pr_project_a8f1e1_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='projects_pr_project_5b8833_idx',
            old_name='projects_pr_project_8e0b3f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='projects_pr_user_id_5f83f5_idx',
            old_name='projects_pr_user_id_3f5a5e_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttask',
            new_name='projects_pr_project_4795b4_idx',
            old_name='projects_pr_project_2dfb2d_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttask',
            new_name='projects_pr_assigne_9e900c_idx',
            old_name='projects_pr_assigne_45c5e2_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttimeentry',
            new_name='projects_pr_project_ecd8ee_idx',
            old_name='projects_pr_project_5d7c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttimeentry',
            new_name='projects_pr_user_id_74b59c_idx',
            old_name='projects_pr_user_id_7b4d3e_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectbudgetline',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
