# Generated by Django 5.2.17 on 2026-09-09 04:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Permission Code')),
                ('name', models.CharField(max_length=150, verbose_name='Permission Name')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='Module')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Role Code')),
                ('name', models.CharField(max_length=100, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.PositiveIntegerField(db_index=True, default=10, verbose_name='Priority Level')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='System Built-in Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('account_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Account Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Locked Until')),
                ('last_password_change', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Password Change')),
                ('force_password_change', models.BooleanField(default=False, verbose_name='Force Password Change')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountLockoutAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Locked At')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Unlocked At')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='Duration (Minutes)')),
                ('reason', models.CharField(max_length=255, verbose_name='Lockout Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Triggering IP')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockout_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Lockout Audit',
                'verbose_name_plural': 'Account Lockout Audits',
                'ordering': ['-locked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_attempted', models.EmailField(db_index=True, max_length=255, verbose_name='Attempted Email')),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful Login'), ('FAILED_INVALID_CREDENTIALS', 'Invalid Credentials'), ('FAILED_ACCOUNT_LOCKED', 'Account Locked'), ('FAILED_ACCOUNT_INACTIVE', 'Account Inactive'), ('FAILED_PASSWORD_EXPIRED', 'Password Expired'), ('LOGOUT', 'Logout')], max_length=50, verbose_name='Login Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Failure Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission Mapping',
                'verbose_name_plural': 'Role Permission Mappings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=20, verbose_name='Theme')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('department_name', models.CharField(blank=True, max_length=100, verbose_name='Department Name')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('notification_inapp', models.BooleanField(default=True, verbose_name='In-App Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'account_status'], name='accounts_us_email_7c4b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['locked_until'], name='accounts_us_locked__febfc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
