# Generated by Django 5.2.17 on 2026-09-09 06:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Legal Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Supplier Code')),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Manufacturer / OEM'), ('distributor', 'Authorized Distributor'), ('wholesaler', 'Wholesaler'), ('service', 'Service Provider / Contractor'), ('raw_materials', 'Raw Materials Supplier')], default='distributor', max_length=30, verbose_name='Supplier Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending Compliance Review'), ('on_hold', 'On Hold / Suspended'), ('disqualified', 'Disqualified')], default='active', max_length=30, verbose_name='Status')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate / Due on Receipt'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net45', 'Net 45 Days'), ('net60', 'Net 60 Days'), ('net90', 'Net 90 Days')], default='net30', max_length=30, verbose_name='Payment Terms')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Default Currency')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / EIN / VAT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Primary Contact Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('website', models.URLField(blank=True, verbose_name='Corporate Website')),
                ('address', models.TextField(blank=True, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='USA', max_length=100, verbose_name='Country')),
                ('lead_time_rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3, verbose_name='Lead Time Rating (1-5)')),
                ('quality_rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3, verbose_name='Quality Rating (1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes & Compliance Requirements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Contact Person Name')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Direct Phone')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Contact',
                'verbose_name_plural': 'Supplier Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(blank=True, max_length=100, verbose_name='Vendor SKU / Part Number')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Supplier Unit Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Minimum Order Quantity (MOQ)')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='Delivery Lead Time (Days)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Designates default vendor for automatic purchase requisition conversion.', verbose_name='Preferred Supplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Offering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offerings', to='sales.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Product Offering',
                'verbose_name_plural': 'Supplier Product Offerings',
                'ordering': ['product__name', 'unit_price'],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
