# Generated by Django 5.2.17 on 2026-09-09 06:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('procurement', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_number', models.CharField(db_index=True, max_length=50, verbose_name='RFQ Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title / Scope')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published / Open for Bids'), ('closed', 'Closed / Bidding Ended'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30, verbose_name='Status')),
                ('submission_deadline', models.DateTimeField(verbose_name='Bid Submission Deadline')),
                ('delivery_deadline', models.DateField(blank=True, null=True, verbose_name='Target Delivery Date')),
                ('notes', models.TextField(blank=True, verbose_name='Procurement Scope & Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Request for Quotation',
                'verbose_name_plural': 'Requests for Quotation',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'rfq_number')},
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Line No.')),
                ('target_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Quantity')),
                ('target_delivery_date', models.DateField(blank=True, null=True, verbose_name='Target Delivery Date')),
                ('specifications', models.TextField(blank=True, verbose_name='Technical Specifications / Scope')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_lines', to='sales.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.requestforquotation')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='sales.unitofmeasure')),
            ],
            options={
                'verbose_name': 'RFQ Line',
                'verbose_name_plural': 'RFQ Lines',
                'ordering': ['line_number'],
                'unique_together': {('rfq', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='VendorBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_reference', models.CharField(max_length=100, verbose_name='Vendor Quote / Reference #')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(verbose_name='Proposal Validity Date')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate / Due on Receipt'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net45', 'Net 45 Days'), ('net60', 'Net 60 Days'), ('net90', 'Net 90 Days')], default='net30', max_length=30, verbose_name='Payment Terms')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='Delivery Lead Time (Days)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Freight / Shipping Cost')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_winning_bid', models.BooleanField(default=False, verbose_name='Awarded Winning Bid')),
                ('award_reason', models.TextField(blank=True, verbose_name='Award Justification / Evaluation')),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Vendor Remarks & Assumptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_bids', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.requestforquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Vendor Bid',
                'verbose_name_plural': 'Vendor Bids',
                'ordering': ['-submission_date'],
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='RFQVendorInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='procurement.requestforquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_invitations', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'RFQ Vendor Invitation',
                'verbose_name_plural': 'RFQ Vendor Invitations',
                'ordering': ['-invited_at'],
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='VendorBidLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Offered Unit Price')),
                ('offered_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Offered Quantity')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='Lead Time (Days)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Vendor Line Remarks')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.vendorbid')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bid_lines', to='procurement.rfqline')),
            ],
            options={
                'verbose_name': 'Vendor Bid Line',
                'verbose_name_plural': 'Vendor Bid Lines',
                'unique_together': {('bid', 'rfq_line')},
            },
        ),
    ]
