# Generated by Django 5.2.17 on 2026-09-09 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('procurement', '0002_requestforquotation_rfqline_vendorbid_and_more'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(db_index=True, max_length=50, verbose_name='PO Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval Gate'), ('approved', 'Approved / Authorized'), ('rejected', 'Rejected'), ('issued', 'Issued to Vendor'), ('partially_received', 'Partially Received'), ('completed', 'Completed / Fully Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30, verbose_name='Status')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate / Due on Receipt'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net45', 'Net 45 Days'), ('net60', 'Net 60 Days'), ('net90', 'Net 90 Days')], default='net30', max_length=30, verbose_name='Payment Terms')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Line Items Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax Amount')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Shipping / Freight')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Commercial Value')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Destination Warehouse / Delivery Address')),
                ('billing_address', models.TextField(blank=True, verbose_name='Billing Address')),
                ('notes', models.TextField(blank=True, verbose_name='Special Instructions & Commercial Terms')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='organizations.organization')),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pos', to='procurement.requestforquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'po_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1: Department Manager (Up to $10,000)'), (2, 'Tier 2: Procurement Director (Up to $50,000)'), (3, 'Tier 3: CFO / Executive Board (Over $50,000)')], default=1, verbose_name='Approval Tier')),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Threshold Amount')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Approval Status')),
                ('comments', models.TextField(blank=True, verbose_name='Comments / Justification')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Approval Gate',
                'verbose_name_plural': 'PO Approval Gates',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Line No.')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ordered Quantity')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Received Quantity')),
                ('billed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Billed Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Line Total')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Line Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='sales.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='sales.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'ordering': ['line_number'],
                'unique_together': {('purchase_order', 'line_number')},
            },
        ),
    ]
