# Generated by Django 5.2.17 on 2026-09-09 06:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('procurement', '0003_purchaseorder_purchaseorderapproval_and_more'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(db_index=True, max_length=100, verbose_name='Vendor Invoice / Bill #')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_match', 'Pending 3-Way Match'), ('matched', 'Matched & Approved for Payment'), ('disputed', 'Disputed / Variance Flagged'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30, verbose_name='Status')),
                ('match_status', models.CharField(choices=[('matched', 'Perfect 3-Way Match'), ('tolerance_accepted', 'Within Commercial Tolerance'), ('price_variance', 'Price Variance Flagged'), ('quantity_variance', 'Quantity Variance Flagged'), ('disputed', 'Disputed'), ('resolved', 'Resolved / Authorized Override')], db_index=True, default='matched', max_length=30, verbose_name='3-Way Match Status')),
                ('bill_date', models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Invoiced Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, verbose_name='Invoice Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='organizations.organization')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Vendor Bill',
                'verbose_name_plural': 'Vendor Bills',
                'ordering': ['-bill_date'],
                'unique_together': {('organization', 'supplier', 'bill_number')},
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Perfect 3-Way Match'), ('tolerance_accepted', 'Within Commercial Tolerance'), ('price_variance', 'Price Variance Flagged'), ('quantity_variance', 'Quantity Variance Flagged'), ('disputed', 'Disputed'), ('resolved', 'Resolved / Authorized Override')], default='matched', max_length=30, verbose_name='Match Outcome')),
                ('po_total_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='PO Total Quantity')),
                ('warehouse_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Warehouse Received Quantity')),
                ('invoice_billed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Invoice Billed Quantity')),
                ('quantity_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantity Variance')),
                ('po_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='PO Amount')),
                ('billed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Billed Amount')),
                ('price_variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Price Variance ($)')),
                ('is_within_tolerance', models.BooleanField(default=True, verbose_name='Within Commercial Tolerance')),
                ('dispute_reason', models.TextField(blank=True, verbose_name='Dispute / Variance Details')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Justification')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_matches', to='organizations.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_matches', to='procurement.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_matches', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_matches', to='procurement.vendorbill')),
            ],
            options={
                'verbose_name': 'Three-Way Match',
                'verbose_name_plural': 'Three-Way Matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billed_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Billed Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Billed Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Line Total')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Line Notes')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.vendorbill')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='procurement.purchaseorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='sales.product')),
            ],
            options={
                'verbose_name': 'Vendor Bill Line',
                'verbose_name_plural': 'Vendor Bill Lines',
            },
        ),
    ]
