# Generated by Django 5.2.17 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_vendorbill_threewaymatch_vendorbillline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vendorbid',
            name='currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='Currency'),
        ),
    ]
