# Generated by Django 5.2.17 on 2026-09-09 06:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Fiscal Year 2026', max_length=100)),
                ('code', models.CharField(help_text='e.g., FY2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant organization', on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.PositiveSmallIntegerField(help_text='1 to 12 (or 13 for year-end)')),
                ('name', models.CharField(help_text='e.g., Period 01 - Jan 2026', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='organizations.organization')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.fiscalyear')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['fiscal_year', 'period_number'],
                'unique_together': {('fiscal_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Accounting account number, e.g. 1010, 2000, 4000', max_length=30)),
                ('name', models.CharField(help_text='Account name, e.g. Cash in Bank, Accounts Payable', max_length=150)),
                ('category', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue / Income'), ('expense', 'Expense / Cost')], max_length=20)),
                ('subtype', models.CharField(choices=[('cash', 'Cash & Equivalents'), ('bank', 'Bank Account'), ('receivable', 'Accounts Receivable (AR)'), ('current_asset', 'Other Current Asset'), ('inventory', 'Inventory Asset'), ('fixed_asset', 'Property, Plant & Equipment'), ('depreciation', 'Accumulated Depreciation'), ('non_current_asset', 'Non-Current Asset'), ('payable', 'Accounts Payable (AP)'), ('current_liability', 'Other Current Liability'), ('tax_payable', 'Tax / VAT Payable'), ('non_current_liability', 'Long-Term Liability'), ('equity_capital', 'Share / Owners Capital'), ('retained_earnings', 'Retained Earnings'), ('current_year_earnings', 'Current Year Earnings'), ('operating_revenue', 'Operating Revenue / Sales'), ('other_income', 'Other Income / Gains'), ('cogs', 'Cost of Goods Sold (COGS)'), ('operating_expense', 'Operating Expense (OPEX)'), ('payroll_expense', 'Salaries & Payroll'), ('depreciation_expense', 'Depreciation & Amortization'), ('financial_expense', 'Interest & Finance Charges'), ('tax_expense', 'Income Tax Expense'), ('other_expense', 'Other Expense / Losses')], max_length=40)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_reconciliation', models.BooleanField(default=False, help_text='If True, acts as an AR/AP control reconciliation account')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_direct_posting', models.BooleanField(default=True, help_text='If False, acts purely as a header/rollup folder account')),
                ('description', models.TextField(blank=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cumulative posted balance adhering to normal debit/credit sign', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchical reporting trees', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.glaccount')),
            ],
            options={
                'verbose_name': 'GL Account',
                'verbose_name_plural': 'GL Accounts',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(help_text='e.g. JE-2026-00001', max_length=50)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='External voucher, check, or invoice ref', max_length=100)),
                ('source_document_type', models.CharField(choices=[('manual', 'Manual General Journal'), ('sales_invoice', 'Sales Customer Invoice'), ('vendor_bill', 'Vendor Bill Payable'), ('inventory_valuation', 'Inventory Stock Valuation'), ('payment', 'Cash / Bank Payment'), ('receipt', 'Customer Payment Receipt'), ('reversal', 'Off-Setting Journal Reversal'), ('closing', 'Fiscal Period / Year Closing')], default='manual', max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft (Unposted)'), ('posted', 'Posted to General Ledger'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('narration', models.TextField(help_text='Detailed transaction explanation / audit memo')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_balanced', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='finance.fiscalperiod')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversed_by_entry', models.ForeignKey(blank=True, help_text='Link to the counter-balancing journal entry if reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_entry', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-entry_number'],
                'unique_together': {('organization', 'entry_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('partner_name', models.CharField(blank=True, help_text='Optional Customer or Supplier memo', max_length=200)),
                ('cost_center', models.CharField(blank=True, help_text='Optional cost center / division tag', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.glaccount')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['line_number'],
            },
        ),
    ]
