# Generated by Django 5.2.17 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
