import uuid
from django.conf import settings
from django.db import models
from django.utils import timezone
class Channel(models.TextChoices):
    IN_APP='in_app','In-App'; EMAIL='email','Email'; SMS='sms','SMS'; WEBHOOK='webhook','Webhook'
class DeliveryStatus(models.TextChoices):
    QUEUED='queued','Queued'; SENT='sent','Sent'; DELIVERED='delivered','Delivered'; FAILED='failed','Failed'; SKIPPED='skipped','Skipped'
class NotificationPriority(models.TextChoices):
    LOW='low','Low'; NORMAL='normal','Normal'; HIGH='high','High'; URGENT='urgent','Urgent'
class NotificationTemplate(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_templates'); name=models.CharField(max_length=160); code=models.SlugField(max_length=90); channel=models.CharField(max_length=20,choices=Channel.choices); subject_template=models.CharField(max_length=240,blank=True); body_template=models.TextField(); variables=models.JSONField(default=list); version=models.PositiveIntegerField(default=1); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: unique_together=('organization','code','version')
class NotificationPreference(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_preferences'); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='notification_preferences'); event_code=models.CharField(max_length=100); channel=models.CharField(max_length=20,choices=Channel.choices); enabled=models.BooleanField(default=True); quiet_start=models.TimeField(null=True,blank=True); quiet_end=models.TimeField(null=True,blank=True); digest_enabled=models.BooleanField(default=False); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: unique_together=('organization','user','event_code','channel')
class Notification(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notifications'); recipient=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='notifications'); event_code=models.CharField(max_length=100,db_index=True); title=models.CharField(max_length=240); message=models.TextField(); link=models.CharField(max_length=500,blank=True); priority=models.CharField(max_length=20,choices=NotificationPriority.choices,default=NotificationPriority.NORMAL); data=models.JSONField(default=dict); is_read=models.BooleanField(default=False); read_at=models.DateTimeField(null=True,blank=True); expires_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: ordering=('-created_at',); indexes=[models.Index(fields=('recipient','is_read')),models.Index(fields=('organization','event_code','created_at'))]
    def mark_read(self): self.is_read=True; self.read_at=timezone.now(); self.save(update_fields=['is_read','read_at'])
class NotificationDelivery(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); notification=models.ForeignKey(Notification,on_delete=models.CASCADE,related_name='deliveries'); channel=models.CharField(max_length=20,choices=Channel.choices); status=models.CharField(max_length=20,choices=DeliveryStatus.choices,default=DeliveryStatus.QUEUED); attempt_count=models.PositiveIntegerField(default=0); provider_message_id=models.CharField(max_length=180,blank=True); error_message=models.TextField(blank=True); queued_at=models.DateTimeField(default=timezone.now); sent_at=models.DateTimeField(null=True,blank=True); delivered_at=models.DateTimeField(null=True,blank=True); next_retry_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: unique_together=('notification','channel'); indexes=[models.Index(fields=('status','next_retry_at'))]
class NotificationBatch(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_batches'); name=models.CharField(max_length=180); event_code=models.CharField(max_length=100); total_count=models.PositiveIntegerField(default=0); sent_count=models.PositiveIntegerField(default=0); failed_count=models.PositiveIntegerField(default=0); status=models.CharField(max_length=20,default='queued'); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); created_at=models.DateTimeField(auto_now_add=True); completed_at=models.DateTimeField(null=True,blank=True)
class Reminder(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='reminders'); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='reminders'); title=models.CharField(max_length=240); message=models.TextField(blank=True); remind_at=models.DateTimeField(); repeat_rule=models.CharField(max_length=80,blank=True); is_completed=models.BooleanField(default=False); completed_at=models.DateTimeField(null=True,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.SET_NULL,related_name='created_reminders'); created_at=models.DateTimeField(auto_now_add=True)
class ScheduledNotification(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='scheduled_notifications'); template=models.ForeignKey(NotificationTemplate,null=True,on_delete=models.SET_NULL); recipient_ids=models.JSONField(default=list); context=models.JSONField(default=dict); channel=models.CharField(max_length=20,choices=Channel.choices); scheduled_for=models.DateTimeField(); status=models.CharField(max_length=20,default='scheduled'); processed_at=models.DateTimeField(null=True,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); created_at=models.DateTimeField(auto_now_add=True)
class NotificationRule(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_rules'); name=models.CharField(max_length=180); event_code=models.CharField(max_length=100); condition=models.JSONField(default=dict,blank=True); template=models.ForeignKey(NotificationTemplate,null=True,on_delete=models.SET_NULL,related_name='rules'); channels=models.JSONField(default=list); recipient_strategy=models.CharField(max_length=80,default='actor'); recipient_config=models.JSONField(default=dict); priority=models.CharField(max_length=20,choices=NotificationPriority.choices,default=NotificationPriority.NORMAL); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True)
class EventSubscription(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='event_subscriptions'); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='event_subscriptions'); event_code=models.CharField(max_length=100); filters=models.JSONField(default=dict,blank=True); channels=models.JSONField(default=list); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: unique_together=('organization','user','event_code')
class UserNotificationDigest(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_digests'); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='notification_digests'); period_start=models.DateTimeField(); period_end=models.DateTimeField(); notification_ids=models.JSONField(default=list); channel=models.CharField(max_length=20,choices=Channel.choices,default=Channel.EMAIL); status=models.CharField(max_length=20,default='pending'); generated_at=models.DateTimeField(null=True,blank=True); sent_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
class NotificationAuditEvent(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='notification_audits'); actor=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); event_code=models.CharField(max_length=100); action=models.CharField(max_length=80); notification=models.ForeignKey(Notification,null=True,blank=True,on_delete=models.SET_NULL); details=models.JSONField(default=dict); created_at=models.DateTimeField(auto_now_add=True)
