import uuid
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
class ComponentType(models.TextChoices): EARNING='earning','Earning'; DEDUCTION='deduction','Deduction'; EMPLOYER_COST='employer_cost','Employer Cost'
class CalculationMethod(models.TextChoices): FIXED='fixed','Fixed'; PERCENTAGE='percentage','Percentage'; FORMULA='formula','Formula'
class PayrollStatus(models.TextChoices): DRAFT='draft','Draft'; PROCESSING='processing','Processing'; PROCESSED='processed','Processed'; APPROVED='approved','Approved'; PAID='paid','Paid'; CANCELLED='cancelled','Cancelled'
class PayrollComponent(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='payroll_components'); name=models.CharField(max_length=120); code=models.CharField(max_length=40); component_type=models.CharField(max_length=20,choices=ComponentType.choices); calculation_method=models.CharField(max_length=20,choices=CalculationMethod.choices,default=CalculationMethod.FIXED); default_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); percentage=models.DecimalField(max_digits=7,decimal_places=4,default=0); taxable=models.BooleanField(default=True); recurring=models.BooleanField(default=True); formula=models.TextField(blank=True); description=models.TextField(blank=True); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: unique_together=('organization','code')
class SalaryStructure(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='salary_structures'); name=models.CharField(max_length=120); code=models.CharField(max_length=40); description=models.TextField(blank=True); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: unique_together=('organization','code')
class SalaryStructureLine(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); structure=models.ForeignKey(SalaryStructure,on_delete=models.CASCADE,related_name='lines'); component=models.ForeignKey(PayrollComponent,on_delete=models.PROTECT,related_name='structure_lines'); sequence=models.PositiveIntegerField(default=1); calculation_method=models.CharField(max_length=20,choices=CalculationMethod.choices); amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); percentage=models.DecimalField(max_digits=7,decimal_places=4,default=0); base_component=models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True,related_name='percentage_children'); min_amount=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); max_amount=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True)
    class Meta: unique_together=('structure','component'); ordering=('sequence',)
class EmployeeSalaryAssignment(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); employee=models.ForeignKey('hr.Employee',on_delete=models.CASCADE,related_name='salary_assignments'); structure=models.ForeignKey(SalaryStructure,on_delete=models.PROTECT,related_name='employee_assignments'); effective_from=models.DateField(); effective_to=models.DateField(null=True,blank=True); monthly_base=models.DecimalField(max_digits=14,decimal_places=2); currency=models.CharField(max_length=10,default='USD'); reason=models.CharField(max_length=255,blank=True); approved_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
class PayrollPeriod(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); organization=models.ForeignKey('organizations.Organization',on_delete=models.CASCADE,related_name='payroll_periods'); name=models.CharField(max_length=100); code=models.CharField(max_length=30); start_date=models.DateField(); end_date=models.DateField(); pay_date=models.DateField(); status=models.CharField(max_length=20,choices=PayrollStatus.choices,default=PayrollStatus.DRAFT); processed_at=models.DateTimeField(null=True,blank=True); processed_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='processed_payroll_periods'); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: unique_together=('organization','code'); ordering=('-start_date',)
    def clean(self):
        if self.end_date<self.start_date: raise ValidationError('Payroll period end must follow start.')
        if self.pay_date<self.end_date: raise ValidationError('Pay date must be on or after period end.')
class Payslip(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); period=models.ForeignKey(PayrollPeriod,on_delete=models.CASCADE,related_name='payslips'); employee=models.ForeignKey('hr.Employee',on_delete=models.PROTECT,related_name='payslips'); payslip_number=models.CharField(max_length=70); gross_pay=models.DecimalField(max_digits=14,decimal_places=2,default=0); total_deductions=models.DecimalField(max_digits=14,decimal_places=2,default=0); employer_cost=models.DecimalField(max_digits=14,decimal_places=2,default=0); net_pay=models.DecimalField(max_digits=14,decimal_places=2,default=0); working_days=models.DecimalField(max_digits=6,decimal_places=2,default=0); paid_days=models.DecimalField(max_digits=6,decimal_places=2,default=0); unpaid_days=models.DecimalField(max_digits=6,decimal_places=2,default=0); status=models.CharField(max_length=20,choices=PayrollStatus.choices,default=PayrollStatus.DRAFT); notes=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: unique_together=('period','employee')
class PayslipLine(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); payslip=models.ForeignKey(Payslip,on_delete=models.CASCADE,related_name='lines'); component=models.ForeignKey(PayrollComponent,on_delete=models.PROTECT,related_name='payslip_lines'); description=models.CharField(max_length=200); component_type=models.CharField(max_length=20,choices=ComponentType.choices); quantity=models.DecimalField(max_digits=10,decimal_places=2,default=1); rate=models.DecimalField(max_digits=14,decimal_places=2,default=0); amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); taxable_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); sequence=models.PositiveIntegerField(default=1)
class PayrollAdjustment(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); employee=models.ForeignKey('hr.Employee',on_delete=models.CASCADE,related_name='payroll_adjustments'); period=models.ForeignKey(PayrollPeriod,on_delete=models.CASCADE,related_name='adjustments'); component=models.ForeignKey(PayrollComponent,on_delete=models.PROTECT,related_name='adjustments'); amount=models.DecimalField(max_digits=14,decimal_places=2); reason=models.CharField(max_length=255); approved=models.BooleanField(default=False); approved_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='created_payroll_adjustments'); created_at=models.DateTimeField(auto_now_add=True)
class PayrollPayment(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); payslip=models.OneToOneField(Payslip,on_delete=models.PROTECT,related_name='payment'); payment_reference=models.CharField(max_length=80); payment_date=models.DateField(); amount=models.DecimalField(max_digits=14,decimal_places=2); bank_reference=models.CharField(max_length=120,blank=True); status=models.CharField(max_length=20,default='pending',choices=(('pending','Pending'),('completed','Completed'),('failed','Failed'))); processed_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True); processed_at=models.DateTimeField(null=True,blank=True)
class PayrollRunAudit(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); period=models.ForeignKey(PayrollPeriod,on_delete=models.CASCADE,related_name='audit_events'); action=models.CharField(max_length=80); message=models.TextField(); actor=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
