# Generated by Django 5.2.17 on 2026-09-09 05:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Warehouse Name')),
                ('code', models.CharField(max_length=50, verbose_name='Warehouse Code')),
                ('warehouse_type', models.CharField(choices=[('distribution_center', 'Distribution Center'), ('manufacturing_plant', 'Manufacturing Plant'), ('retail_store', 'Retail Outlet / Store'), ('transit_hub', 'Transit / Cross-Dock Hub'), ('quarantine_facility', 'Quarantine & Inspection Facility')], default='distribution_center', max_length=40, verbose_name='Warehouse Type')),
                ('address', models.TextField(blank=True, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='USA', max_length=100, verbose_name='Country')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates the primary fulfillment node for standard order allocation.', verbose_name='Primary Headquarters Facility')),
                ('total_capacity_cbm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total usable storage volume in cubic meters.', max_digits=12, verbose_name='Capacity (Cubic Meters)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='organizations.branch')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('code', models.CharField(max_length=30, verbose_name='Zone Code')),
                ('zone_type', models.CharField(choices=[('general', 'General Storage'), ('cold_storage', 'Cold / Refrigerated Storage'), ('hazardous', 'Hazardous Materials (HazMat)'), ('bulk_storage', 'Bulk / High-Bay Storage'), ('receiving', 'Inbound Receiving Dock'), ('shipping', 'Outbound Staging & Shipping'), ('picking', 'Fast-Pick Forward Area'), ('quarantine', 'Quality Quarantine & Inspection')], default='general', max_length=30, verbose_name='Zone Classification')),
                ('temperature_controlled', models.BooleanField(default=False, verbose_name='Temperature Controlled')),
                ('target_temp_celsius', models.DecimalField(blank=True, decimal_places=2, help_text='Operating temperature threshold if climate-controlled.', max_digits=5, null=True, verbose_name='Target Temp (°C)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Storage Zone',
                'verbose_name_plural': 'Storage Zones',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=60, verbose_name='Location Identifier Code')),
                ('aisle', models.CharField(default='01', max_length=20, verbose_name='Aisle')),
                ('rack', models.CharField(default='01', max_length=20, verbose_name='Rack / Bay')),
                ('shelf', models.CharField(default='01', max_length=20, verbose_name='Shelf / Tier')),
                ('bin', models.CharField(default='01', max_length=20, verbose_name='Bin / Position')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Barcode Identifier')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Max Weight (kg)')),
                ('max_volume_cbm', models.DecimalField(decimal_places=3, default=Decimal('2.000'), max_digits=8, verbose_name='Max Volume (m³)')),
                ('is_locked', models.BooleanField(default=False, help_text='Disables putaway and picking during cycle count or maintenance.', verbose_name='Locked')),
                ('lock_reason', models.CharField(blank=True, max_length=255, verbose_name='Lock Reason')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='organizations.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.storagezone')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total physical items present in storage.', max_digits=12, verbose_name='Quantity On-Hand')),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Items allocated to confirmed sales orders awaiting picking.', max_digits=12, verbose_name='Quantity Reserved')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Buffer quantity below which emergency procurement is required.', max_digits=10, verbose_name='Safety Stock Buffer')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Inventory level triggering standard restocking requisition.', max_digits=10, verbose_name='Reorder Point Threshold')),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Standard replenishment batch order quantity.', max_digits=10, verbose_name='Economic Reorder Quantity (EOQ)')),
                ('last_counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Physical Audit Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='sales.product')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.storagelocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Item Level',
                'verbose_name_plural': 'Stock Item Levels',
                'ordering': ['product__name', 'warehouse__code'],
                'unique_together': {('warehouse', 'location', 'product')},
            },
        ),
    ]
