# Generated by Django 5.2.17 on 2026-09-09 05:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(db_index=True, max_length=64, verbose_name='Movement Number')),
                ('movement_type', models.CharField(choices=[('receipt', 'Inbound Goods Receipt'), ('transfer', 'Warehouse Transfer'), ('location_transfer', 'Internal Location Relocation'), ('adjustment', 'Inventory Adjustment / Variance'), ('scrap', 'Damaged / Scrap Write-Off'), ('return', 'Customer / Vendor Return')], default='receipt', max_length=30, verbose_name='Movement Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('completed', 'Completed / Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Status')),
                ('reference_document', models.CharField(blank=True, help_text='External PO number, Sales Order, RMA, or Audit Count ID.', max_length=100, verbose_name='Reference Document')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movement Date')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes & Operational Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Destination facility for receipts, inbound transfers, and returns.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_movements', to='inventory.warehouse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(blank=True, help_text='Origin facility for transfers, scrap, and negative adjustments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'movement_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity Moved')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Unit Cost')),
                ('batch_number', models.CharField(blank=True, max_length=60, verbose_name='Batch / Lot #')),
                ('serial_number', models.CharField(blank=True, max_length=60, verbose_name='Serial Number')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Line Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_movement_lines', to='inventory.storagelocation')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_lines', to='sales.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movement_lines', to='inventory.storagelocation')),
            ],
            options={
                'verbose_name': 'Stock Movement Line',
                'verbose_name_plural': 'Stock Movement Lines',
                'ordering': ['created_at'],
            },
        ),
    ]
