# Generated by Django 5.2.17 on 2026-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_stockmovementline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Movement Number'),
        ),
    ]
