# Generated by Django 5.2.17 on 2026-09-09 05:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_number'),
        ('organizations', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=80, verbose_name='Lot / Batch Code')),
                ('supplier_lot_number', models.CharField(blank=True, max_length=80, verbose_name='Supplier Lot Identifier')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiration Date')),
                ('qc_status', models.CharField(choices=[('quarantined', 'Under Quarantine / Pending Inspection'), ('approved', 'QC Approved / Released'), ('rejected', 'QC Rejected / Non-Conforming'), ('expired', 'Expired / Disposition Required')], default='approved', max_length=30, verbose_name='Quality Control Status')),
                ('qc_inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='QC Inspection Timestamp')),
                ('qc_notes', models.TextField(blank=True, verbose_name='QC Findings / Lab Notes')),
                ('certificate_of_analysis', models.CharField(blank=True, max_length=255, verbose_name='CoA Document Ref / URL')),
                ('initial_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Initial Received Quantity')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Current Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_batches', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='sales.product')),
                ('qc_inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_inspected_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot / Batch',
                'verbose_name_plural': 'Lots / Batches',
                'ordering': ['expiration_date', '-created_at'],
                'unique_together': {('organization', 'product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='Serial Number Identifier')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock / Available'), ('reserved', 'Reserved for Order'), ('dispatched', 'Dispatched / Sold'), ('consumed', 'Consumed in Manufacturing'), ('returned', 'Returned by Customer'), ('defective', 'Defective / Damaged')], default='in_stock', max_length=30, verbose_name='Serial Status')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='Warranty Start Date')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Warranty Expiration Date')),
                ('notes', models.TextField(blank=True, verbose_name='Unit Service History / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='inventory.storagelocation')),
                ('lot', models.ForeignKey(blank=True, help_text='Associated production lot or batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='inventory.lotbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='sales.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
                'ordering': ['product__name', 'serial_number'],
                'unique_together': {('organization', 'product', 'serial_number')},
            },
        ),
    ]
