# Generated by Django 5.2.17 on 2026-09-09 05:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_lotbatch_serialnumber'),
        ('organizations', '0001_initial'),
        ('sales', '0003_salesorder_orderstatushistory_orderlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Requisition Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved for Procurement'), ('converted', 'Converted to Purchase Order'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low / Scheduled Stocking'), ('medium', 'Medium / Standard Reorder'), ('high', 'High / Urgent Stockout Threat'), ('critical', 'Critical / Immediate Line Down')], default='medium', max_length=30, verbose_name='Priority')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Required Delivery Date')),
                ('justification', models.TextField(blank=True, verbose_name='Business Justification & Context')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'requisition_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity Requested')),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estimated Unit Cost')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Specification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_lines', to='sales.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaserequisition')),
            ],
            options={
                'verbose_name': 'Requisition Line',
                'verbose_name_plural': 'Requisition Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Quantity at which a replenishment trigger is fired.', max_digits=10, verbose_name='Minimum Stock Threshold')),
                ('max_quantity', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Ceiling quantity to prevent overstocking.', max_digits=10, verbose_name='Target Maximum Capacity')),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Recommended order batch quantity.', max_digits=10, verbose_name='Replenishment Batch Size (EOQ)')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Estimated vendor delivery turnaround in calendar days.', verbose_name='Lead Time (Days)')),
                ('auto_reorder_enabled', models.BooleanField(default=True, verbose_name='Auto-Generate Requisition')),
                ('preferred_vendor_name', models.CharField(blank=True, max_length=150, verbose_name='Preferred Supplier / Vendor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='sales.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Reorder Policy',
                'verbose_name_plural': 'Reorder Policies',
                'ordering': ['warehouse__code', 'product__name'],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
