# Generated by Django 5.2.17 on 2026-09-09 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Account Name')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Strategic Partner'), ('VENDOR', 'Vendor / Supplier'), ('RESELLER', 'Value-Added Reseller'), ('COMPETITOR', 'Competitor'), ('OTHER', 'Other')], db_index=True, default='PROSPECT', max_length=32, verbose_name='Account Type')),
                ('industry', models.CharField(choices=[('TECHNOLOGY', 'Technology & Software'), ('FINANCE', 'Banking & Financial Services'), ('HEALTHCARE', 'Healthcare & Pharmaceuticals'), ('MANUFACTURING', 'Manufacturing & Industrial'), ('RETAIL', 'Retail & Consumer Goods'), ('EDUCATION', 'Education & Academia'), ('GOVERNMENT', 'Government & Public Sector'), ('TELECOM', 'Telecommunications'), ('ENERGY', 'Energy & Utilities'), ('CONSULTING', 'Professional & Consulting Services'), ('MEDIA', 'Media & Entertainment'), ('REAL_ESTATE', 'Real Estate & Construction'), ('OTHER', 'Other Industry')], db_index=True, default='TECHNOLOGY', max_length=32, verbose_name='Industry')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Annual Revenue')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee Count')),
                ('website', models.URLField(blank=True, verbose_name='Corporate Website')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Primary Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='General Email')),
                ('billing_address_line1', models.CharField(blank=True, max_length=255, verbose_name='Billing Address 1')),
                ('billing_address_line2', models.CharField(blank=True, max_length=255, verbose_name='Billing Address 2')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Billing City')),
                ('billing_state', models.CharField(blank=True, max_length=100, verbose_name='Billing State / Province')),
                ('billing_postal_code', models.CharField(blank=True, max_length=32, verbose_name='Billing Postal Code')),
                ('billing_country', models.CharField(blank=True, max_length=100, verbose_name='Billing Country')),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255, verbose_name='Shipping Address 1')),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255, verbose_name='Shipping Address 2')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='Shipping City')),
                ('shipping_state', models.CharField(blank=True, max_length=100, verbose_name='Shipping State / Province')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=32, verbose_name='Shipping Postal Code')),
                ('shipping_country', models.CharField(blank=True, max_length=100, verbose_name='Shipping Country')),
                ('lifecycle_stage', models.CharField(choices=[('LEAD', 'Lead'), ('MQL', 'Marketing Qualified Lead (MQL)'), ('SQL', 'Sales Qualified Lead (SQL)'), ('OPPORTUNITY', 'Opportunity / In Pipeline'), ('CUSTOMER', 'Active Customer'), ('EVANGELIST', 'Evangelist / Advocate'), ('CHURNED', 'Churned Customer')], db_index=True, default='LEAD', max_length=32, verbose_name='Lifecycle Stage')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=32, verbose_name='Account Status')),
                ('description', models.TextField(blank=True, verbose_name='Description / Background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_accounts', to='organizations.organization', verbose_name='Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Direct Phone')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='Mobile Phone')),
                ('job_title', models.CharField(blank=True, max_length=128, verbose_name='Job Title')),
                ('department', models.CharField(blank=True, max_length=128, verbose_name='Department')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Primary Contact Flag')),
                ('do_not_call', models.BooleanField(default=False, verbose_name='Do Not Call')),
                ('do_not_email', models.BooleanField(default=False, verbose_name='Do Not Email')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('lifecycle_stage', models.CharField(choices=[('LEAD', 'Lead'), ('MQL', 'Marketing Qualified Lead (MQL)'), ('SQL', 'Sales Qualified Lead (SQL)'), ('OPPORTUNITY', 'Opportunity / In Pipeline'), ('CUSTOMER', 'Active Customer'), ('EVANGELIST', 'Evangelist / Advocate'), ('CHURNED', 'Churned Customer')], default='LEAD', max_length=32, verbose_name='Lifecycle Stage')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.account', verbose_name='Account / Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='organizations.organization', verbose_name='Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Contact Owner')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'name'], name='crm_account_organiz_068c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'status'], name='crm_account_organiz_3f7727_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'lifecycle_stage'], name='crm_account_organiz_9a1dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'account_type'], name='crm_account_organiz_e76f25_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='crm_contact_organiz_4a6a71_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='crm_contact_organiz_d7c182_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'is_primary_contact'], name='crm_contact_account_cfdbb1_idx'),
        ),
    ]
