# Generated by Django 5.2.17 on 2026-09-09 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, max_length=128, verbose_name='Job Title')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Company Website')),
                ('lead_source', models.CharField(choices=[('WEBSITE', 'Website Form / Inbound'), ('REFERRAL', 'Client / Partner Referral'), ('COLD_CALL', 'Outbound Cold Call / Outreach'), ('ADVERTISING', 'Online Advertising / SEM'), ('EVENT', 'Trade Show / Conference'), ('PARTNER', 'Channel Partner'), ('SOCIAL_MEDIA', 'Social Media / LinkedIn'), ('OTHER', 'Other Source')], db_index=True, default='WEBSITE', max_length=32, verbose_name='Lead Source')),
                ('status', models.CharField(choices=[('NEW', 'New / Uncontacted'), ('CONTACTED', 'Contacted / In Discussion'), ('QUALIFIED', 'Sales Qualified'), ('UNQUALIFIED', 'Unqualified / Disqualified'), ('CONVERTED', 'Converted to Customer')], db_index=True, default='NEW', max_length=32, verbose_name='Lead Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=16, verbose_name='Priority')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Estimated Deal Value')),
                ('lead_score', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Algorithmic Lead Score (0-100)')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='Score Calculation Breakdown')),
                ('industry', models.CharField(choices=[('TECHNOLOGY', 'Technology & Software'), ('FINANCE', 'Banking & Financial Services'), ('HEALTHCARE', 'Healthcare & Pharmaceuticals'), ('MANUFACTURING', 'Manufacturing & Industrial'), ('RETAIL', 'Retail & Consumer Goods'), ('EDUCATION', 'Education & Academia'), ('GOVERNMENT', 'Government & Public Sector'), ('TELECOM', 'Telecommunications'), ('ENERGY', 'Energy & Utilities'), ('CONSULTING', 'Professional & Consulting Services'), ('MEDIA', 'Media & Entertainment'), ('REAL_ESTATE', 'Real Estate & Construction'), ('OTHER', 'Other Industry')], default='TECHNOLOGY', max_length=32, verbose_name='Industry')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee Count')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Annual Revenue')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('is_converted', models.BooleanField(db_index=True, default=False, verbose_name='Converted Flag')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Conversion Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_leads', to='crm.account', verbose_name='Converted Account')),
                ('converted_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_leads', to='crm.contact', verbose_name='Converted Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='organizations.organization', verbose_name='Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Lead Owner')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-lead_score', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='crm_lead_organiz_0f244d_idx'), models.Index(fields=['organization', 'lead_score'], name='crm_lead_organiz_f9149e_idx'), models.Index(fields=['organization', 'email'], name='crm_lead_organiz_e86ac1_idx'), models.Index(fields=['organization', 'is_converted'], name='crm_lead_organiz_51778d_idx')],
            },
        ),
    ]
