# Generated by Django 5.2.17 on 2026-09-09 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Deal Name')),
                ('deal_number', models.CharField(blank=True, max_length=64, verbose_name='Deal Number')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total Contract Value ($)')),
                ('probability', models.PositiveSmallIntegerField(default=10, verbose_name='Win Probability (%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='Actual Close Date')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Closed Flag')),
                ('is_won', models.BooleanField(db_index=True, default=False, verbose_name='Won Flag')),
                ('lost_reason', models.TextField(blank=True, verbose_name='Reason for Loss')),
                ('description', models.TextField(blank=True, verbose_name='Deal Overview / Scope')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.account', verbose_name='Corporate Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_deals', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_deals', to='organizations.organization', verbose_name='Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_deals', to=settings.AUTH_USER_MODEL, verbose_name='Deal Owner')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact', verbose_name='Primary Contact')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('code', models.CharField(max_length=50, verbose_name='Stage Code')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('default_probability', models.PositiveSmallIntegerField(default=10, verbose_name='Default Win Probability (%)')),
                ('is_won_stage', models.BooleanField(default=False, verbose_name='Closed Won Stage Flag')),
                ('is_lost_stage', models.BooleanField(default=False, verbose_name='Closed Lost Stage Flag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='Badge Color Hex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_pipeline_stages', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealStageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transition_notes', models.TextField(blank=True, verbose_name='Transition Notes')),
                ('duration_in_previous_stage_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in Previous Stage (Seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='crm.deal', verbose_name='Deal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_deal_transitions', to='organizations.organization', verbose_name='Organization')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipelinestage', verbose_name='Previous Stage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.pipelinestage', verbose_name='Target Stage')),
            ],
            options={
                'verbose_name': 'Deal Stage Transition',
                'verbose_name_plural': 'Deal Stage Transitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipelinestage', verbose_name='Current Pipeline Stage'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['organization', 'order'], name='crm_pipelin_organiz_63af93_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['organization', 'is_active'], name='crm_pipelin_organiz_846169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='dealstagetransition',
            index=models.Index(fields=['deal', 'created_at'], name='crm_dealsta_deal_id_6fa7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='dealstagetransition',
            index=models.Index(fields=['organization', 'created_at'], name='crm_dealsta_organiz_d0f729_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'stage'], name='crm_deal_organiz_89b069_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'is_closed'], name='crm_deal_organiz_6f711d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'is_won'], name='crm_deal_organiz_158338_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'is_closed'], name='crm_deal_account_8d6f39_idx'),
        ),
    ]
