# Generated by Django 5.2.17 on 2026-09-09 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_deal_pipelinestage_dealstagetransition_deal_stage_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MEETING', 'Meeting / Conference'), ('TASK', 'To-Do Task'), ('EMAIL', 'Email Correspondence'), ('DEMO', 'Product Demonstration'), ('NOTE', 'General Note')], db_index=True, default='TASK', max_length=32, verbose_name='Activity Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject / Title')),
                ('description', models.TextField(blank=True, verbose_name='Description / Agenda / Notes')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date / Scheduled Time')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion Timestamp')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned / Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=32, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.account', verbose_name='Account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Representative')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal', verbose_name='Deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='Lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='crm_activit_organiz_f33efb_idx'), models.Index(fields=['organization', 'due_date'], name='crm_activit_organiz_abf956_idx'), models.Index(fields=['account', 'status'], name='crm_activit_account_d951bb_idx'), models.Index(fields=['deal', 'status'], name='crm_activit_deal_id_35299b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Note Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='crm.account', verbose_name='Account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='crm.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='crm.deal', verbose_name='Deal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='crm_note_organiz_477d42_idx')],
            },
        ),
    ]
