# Generated by Django 5.2.17 on 2026-09-09 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_user'),
        ('organizations', '0002_alter_organization_currency'),
        ('support', '0001_phase10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cannedresponse',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supportbusinesshour',
            options={'ordering': ('weekday',)},
        ),
        migrations.AlterModelOptions(
            name='supportcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supportteam',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='ticketassignmenthistory',
            options={'ordering': ('-changed_at',)},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='ticketslaevent',
            options={'ordering': ('-occurred_at',)},
        ),
        migrations.AlterModelOptions(
            name='ticketstatushistory',
            options={'ordering': ('-changed_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='cannedresponse',
            unique_together={('organization', 'shortcut')},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticle',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebasecategory',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='supportbusinesshour',
            unique_together={('organization', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='supportcategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='supportteam',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='supportteammember',
            unique_together={('team', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='supportticket',
            unique_together={('organization', 'number')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['organization', 'is_published'], name='support_kno_organiz_88f024_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['organization', 'category'], name='support_kno_organiz_c4e906_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcategory',
            index=models.Index(fields=['organization', 'is_active'], name='support_sup_organiz_1b1c24_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcategory',
            index=models.Index(fields=['organization', 'parent'], name='support_sup_organiz_a9df34_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'status'], name='support_sup_organiz_9f38ac_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'priority'], name='support_sup_organiz_718008_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'assignee', 'status'], name='support_sup_organiz_eff881_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'created_at'], name='support_sup_organiz_1397e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
    ]
