# Generated manually for EnterpriseOne Phase 11.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[('organizations','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='MetricDefinition',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('code',models.SlugField(max_length=80)),('description',models.TextField(blank=True)),('source',models.CharField(choices=[('crm','CRM'),('sales','Sales'),('inventory','Inventory'),('procurement','Procurement'),('finance','Finance'),('hr','HR'),('payroll','Payroll'),('projects','Projects'),('support','Support'),('organizations','Organizations'),('custom','Custom')],max_length=30)),('metric_type',models.CharField(choices=[('count','Count'),('sum','Sum'),('average','Average'),('ratio','Ratio'),('percentage','Percentage'),('currency','Currency'),('duration','Duration')],max_length=20)),('expression',models.TextField()),('unit',models.CharField(blank=True,max_length=30)),('dimensions',models.JSONField(blank=True,default=list)),('filters',models.JSONField(blank=True,default=dict)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_metrics',to='organizations.organization')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='created_metrics',to=settings.AUTH_USER_MODEL))],options={'ordering':('name',),'unique_together':{('organization','code')}}),
        migrations.CreateModel(name='Dashboard',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=180)),('slug',models.SlugField(max_length=220)),('description',models.TextField(blank=True)),('is_default',models.BooleanField(default=False)),('is_shared',models.BooleanField(default=True)),('layout',models.JSONField(blank=True,default=dict)),('filters',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_dashboards',to='organizations.organization')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':('name',),'unique_together':{('organization','slug')}}),
        migrations.CreateModel(name='Report',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=180)),('code',models.SlugField(max_length=100)),('description',models.TextField(blank=True)),('source',models.CharField(choices=[('crm','CRM'),('sales','Sales'),('inventory','Inventory'),('procurement','Procurement'),('finance','Finance'),('hr','HR'),('payroll','Payroll'),('projects','Projects'),('support','Support'),('organizations','Organizations'),('custom','Custom')],max_length=30)),('status',models.CharField(choices=[('draft','Draft'),('active','Active'),('archived','Archived')],default='draft',max_length=20)),('columns',models.JSONField(default=list)),('filters',models.JSONField(blank=True,default=dict)),('group_by',models.JSONField(blank=True,default=list)),('order_by',models.JSONField(blank=True,default=list)),('aggregation',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_reports',to='organizations.organization')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':('-updated_at',),'unique_together':{('organization','code')}}),
        migrations.CreateModel(name='KPI',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('target',models.DecimalField(decimal_places=4,default=0,max_digits=18)),('warning_threshold',models.DecimalField(blank=True,decimal_places=4,max_digits=18,null=True)),('critical_threshold',models.DecimalField(blank=True,decimal_places=4,max_digits=18,null=True)),('is_active',models.BooleanField(default=True)),('display_order',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('metric',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='kpis',to='analytics.metricdefinition')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='kpis',to='organizations.organization')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='owned_kpis',to=settings.AUTH_USER_MODEL))],options={'ordering':('display_order','name'),'unique_together':{('organization','name')}}),
        migrations.CreateModel(name='DashboardPermission',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('can_view',models.BooleanField(default=True)),('can_edit',models.BooleanField(default=False)),('can_share',models.BooleanField(default=False)),('dashboard',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='permissions',to='analytics.dashboard')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dashboard_permissions',to=settings.AUTH_USER_MODEL))],options={'unique_together':{('dashboard','user')}}),
        migrations.CreateModel(name='DashboardWidget',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=180)),('widget_type',models.CharField(choices=[('kpi','KPI'),('table','Table'),('bar','Bar'),('line','Line'),('pie','Pie'),('area','Area'),('funnel','Funnel'),('gauge','Gauge'),('number','Number')],max_length=20)),('configuration',models.JSONField(blank=True,default=dict)),('position',models.JSONField(blank=True,default=dict)),('refresh_seconds',models.PositiveIntegerField(default=300)),('is_visible',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('dashboard',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='widgets',to='analytics.dashboard')),('metric',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='widgets',to='analytics.metricdefinition'))]),
        migrations.CreateModel(name='ReportRun',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('started_at',models.DateTimeField()),('completed_at',models.DateTimeField(blank=True,null=True)),('row_count',models.PositiveIntegerField(default=0)),('duration_ms',models.PositiveIntegerField(default=0)),('status',models.CharField(default='completed',max_length=20)),('parameters',models.JSONField(blank=True,default=dict)),('result_snapshot',models.JSONField(blank=True,default=dict)),('error_message',models.TextField(blank=True)),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='runs',to='analytics.report')),('requested_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ReportSchedule',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('frequency',models.CharField(choices=[('daily','Daily'),('weekly','Weekly'),('monthly','Monthly'),('quarterly','Quarterly')],max_length=20)),('hour',models.PositiveSmallIntegerField(default=8)),('minute',models.PositiveSmallIntegerField(default=0)),('recipients',models.JSONField(default=list)),('export_format',models.CharField(default='csv',max_length=10)),('is_active',models.BooleanField(default=True)),('next_run_at',models.DateTimeField(blank=True,null=True)),('last_run_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='schedules',to='analytics.report'))]),
        migrations.CreateModel(name='AnalyticsSnapshot',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('captured_for',models.DateTimeField()),('value',models.DecimalField(decimal_places=6,default=0,max_digits=20)),('dimensions',models.JSONField(blank=True,default=dict)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('metric',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='snapshots',to='analytics.metricdefinition')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_snapshots',to='organizations.organization'))],options={'ordering':('-captured_for',),'unique_together':{('metric','captured_for')}}),
        migrations.CreateModel(name='AnalyticsAlert',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=180)),('operator',models.CharField(default='lt',max_length=10)),('threshold',models.DecimalField(decimal_places=4,max_digits=18)),('recipients',models.JSONField(default=list)),('is_active',models.BooleanField(default=True)),('last_triggered_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('kpi',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='alerts',to='analytics.kpi')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_alerts',to='organizations.organization'))]),
        migrations.CreateModel(name='AnalyticsAuditEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=60)),('entity_type',models.CharField(max_length=60)),('entity_id',models.CharField(max_length=80)),('details',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='analytics_audit_events',to='organizations.organization'))]),
    ]
