# Generated by Django 5.2.17 on 2026-09-09 10:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0002_alter_organization_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsauditevent',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='dashboardwidget',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='reportrun',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='expression',
            field=models.TextField(help_text='Safe analytics expression describing the calculation.'),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='analyticsauditevent',
            index=models.Index(fields=['organization', 'created_at'], name='analytics_a_organiz_cdae09_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsauditevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__aff1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['organization', 'captured_for'], name='analytics_a_organiz_5971a1_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['metric', 'captured_for'], name='analytics_a_metric__c9f244_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'widget_type'], name='analytics_d_dashboa_ef194f_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdefinition',
            index=models.Index(fields=['organization', 'source'], name='analytics_m_organiz_450772_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdefinition',
            index=models.Index(fields=['organization', 'is_active'], name='analytics_m_organiz_cd37ed_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'source'], name='analytics_r_organiz_a81dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status'], name='analytics_r_organiz_3a11e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['report', 'started_at'], name='analytics_r_report__5a13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='analytics_r_is_acti_9347a8_idx'),
        ),
    ]
