# Generated by Django 5.2.17 on 2026-09-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mlmodel',
            new_name='ai_engine_m_organiz_579ad3_idx',
            old_name='ai_mlmodel_org_proble_5c1a0f_idx',
        ),
        migrations.RenameIndex(
            model_name='mlmodel',
            new_name='ai_engine_m_organiz_22dfe6_idx',
            old_name='ai_mlmodel_org_statu_8b2f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='modelmonitoringmetric',
            new_name='ai_engine_m_model_i_ae5c95_idx',
            old_name='ai_modelmo_model_n_4f3a7b_idx',
        ),
        migrations.RenameIndex(
            model_name='modelversion',
            new_name='ai_engine_m_model_i_f0bc60_idx',
            old_name='ai_modelver_model_i_9e10c0_idx',
        ),
        migrations.RenameIndex(
            model_name='predictionrequest',
            new_name='ai_engine_p_model_i_968ba7_idx',
            old_name='ai_predict_model_i_3f9a34_idx',
        ),
        migrations.RenameIndex(
            model_name='predictionrequest',
            new_name='ai_engine_p_status_1efe65_idx',
            old_name='ai_predict_status_2a7e17_idx',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictionfeedback',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='predictionfeedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='modeldeployment',
            index=models.Index(fields=['environment', 'active'], name='ai_engine_m_environ_455baf_idx'),
        ),
    ]
